openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:

  /categories/{id}:
    get:
      tags:
        - Category
      summary: Get current category
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful displayed all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                      example: 5
                    parent_id:
                      type: integer
                      format: nullable
                    name:
                      type: string
                      example: eligendi
                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    delete:
      tags:
        -  Delete categories
      summary: Delete category
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true

      responses:
        '401':
          $ref: 'exceptions.yaml#/components/responses/userIsNotAuthorize'
        '200':
          description: Successful deleted category
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean
    put:
      tags:
        - Update category
      summary: update current category
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: test Category
      responses:
        '404':
          description: Category is not exist
          content:
            application/json:
              schema:
                example: Category is not found
        '401':
          $ref: 'exceptions.yaml#/components/responses/userIsNotAuthorize'
        '409':
          $ref: 'exceptions.yaml#/components/responses/tokenTimeRunOut'
        '422':
          description: Incorrect entering data
          content:
            application/json:
              schema:
               type: object
              examples:
                NameIsNotString:
                  value:
                    message: 'The name field must be a string.'
                    error:
                        name: 'The name field must be a string.'
                NameIsNotPresent:
                  value:
                    message: 'The name field is required.'
                    error:
                        name: 'The name field is required.'
        '200':
          description: Successful updated category
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                      example: 5
                    parent_id:
                      type: integer
                      format: nullable
                    name:
                      type: string
                      example: eligendi
                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
  /categories:
    post:
      tags:
        -  Create categories
      summary: Create category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: test Category
                parent_id:
                  type: integer
                  example: 3


      responses:
        '401':
          $ref: 'exceptions.yaml#/components/responses/userIsNotAuthorize'
        '409':
          $ref: 'exceptions.yaml#/components/responses/tokenTimeRunOut'
        '422':
          description: Incorrect entering data
          content:
            application/json:
              schema:
               type: object
              examples:
                NameIsNotString:
                  value:
                    message: 'The name field must be a string.'
                    error:
                        name: 'The name field must be a string.'
                NameIsNotPresent:
                  value:
                    message: 'The name field is required.'
                    error:
                        name: 'The name field is required.'

        '200':
          description: Successful created category
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                      example: 5
                    parent_id:
                      type: integer
                      format: nullable
                    name:
                      type: string
                      example: eligendi
                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    get:
      tags:
        - Categories
      summary: Get all categories
      responses:
        '200':
          description: Successful displayed all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                          example: 1
                        parent_id:
                          type: string
                          format: nullable
                        name:
                          type: string
                          example: et
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/categories?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/categories?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/categories?page=2
                  path:
                    type: string
                    example: http://localhost/api/categories
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

