openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:

  /countries/{id}:
    get:
      tags:
        - Country
      summary: Get current country
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '404':
          description: country is not exist
          content:
            application/json:
              schema:
                example: country is not found
        '200':
          description: Successful displayed all countries
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                      example: 5
                    name:
                      type: string
                      example: eligendi
                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    delete:
      tags:
        -  Delete countries
      summary: Delete country
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      security:
        - BearerToken: [ ]
      responses:

        '404':
          description: country is not exist
          content:
            application/json:
              schema:
                example: country is not found
        '401':
          $ref: 'exceptions.yaml#/components/responses/adminIsNotAuthorize'
        '200':
          description: Successful deleted country
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean
    put:
      tags:
        - Update country
      summary: update current country
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      security:
        - BearerToken: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: test Country
      responses:

        '422':
          description: Incorrect entering data
          content:
            application/json:
              schema:
               type: object
              examples:
                ContentIsNotString:
                  value:
                    message: 'The name field must be a string.'
                    error:
                        name: 'The name field must be a string.'
                ContentIsNotPresent:
                  value:
                    message: 'The name field is required.'
                    error:
                        name: 'The name field is required.'
        '404':
          description: country is not exist
          content:
            application/json:
              schema:
                example: country is not found
        '401':
          $ref: 'exceptions.yaml#/components/responses/adminIsNotAuthorize'
        '200':
          description: Successful updated country
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                      example: 5
                    name:
                      type: string
                      example: eligendi
                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
  /countries:
    post:
      tags:
        -  Create countries
      summary: Create country

      security:
        - BearerToken: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: test Country


      responses:

        '422':
          description: Incorrect entering data
          content:
            application/json:
              schema:
               type: object
              examples:
                ContentIsNotString:
                  value:
                    message: 'The name field must be a string.'
                    error:
                        name: 'The name field must be a string.'
                ContentIsNotPresent:
                  value:
                    message: 'The name field is required.'
                    error:
                        name: 'The name field is required.'
        '401':
          $ref: 'exceptions.yaml#/components/responses/adminIsNotAuthorize'
        '200':
          description: Successful created country
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                      example: 5
                    name:
                      type: string
                      example: eligendi
                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    get:
      tags:
        - Countries
      summary: Get all countries
      responses:
        '200':
          description: Successful displayed all countries
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int32
                          example: 1
                        name:
                          type: string
                          example: et
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/countries?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/countries?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/countries?page=2
                  path:
                    type: string
                    example: http://localhost/api/countries
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

