openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:

  /questions/{id}:
    get:
      tags:
        - Question
      summary: Get current question
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '404':
          description: Question is not exist
          content:
            application/json:
              schema:
                example: Question is not found
        '200':
          description: Successful displayed all questions
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true


                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
    put:
      tags:
        - Update question
      summary: update current question
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      security:
        - BearerToken: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '422':
          description: Incorrect entering data
          content:
            application/json:
              schema:
               type: object
              examples:
                ContentIsNotString:
                  value:
                    message: 'The content field must be a string.'
                    error:
                        content: 'The content field must be a string.'
                ContentIsNotPresent:
                  value:
                    message: 'The content field is required.'
                    error:
                        content: 'The content field is required.'
        '404':
          description: Question is not exist
          content:
            application/json:
              schema:
                example: Question is not found
        '200':
          description: Successful updated question
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
    delete:
      tags:
        -  Delete questions
      summary: Delete question
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      security:
        - BearerToken: [ ]
      responses:
        '404':
          description: Question is not exist
          content:
            application/json:
              schema:
                example: Question is not found
        '200':
          description: Successful deleted question
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean
  /events/{id}/questions:
    post:
      tags:
        -  Create questions
      summary: Create question
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      security:
        - BearerToken: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                    content:
                      type: string
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true


      responses:
        '422':
          description: Incorrect entering data
          content:
            application/json:
              schema:
               type: object
              examples:
                ContentIsNotString:
                  value:
                    message: 'The content field must be a string.'
                    error:
                        content: 'The content field must be a string.'
                ContentIsNotPresent:
                  value:
                    message: 'The content field is required.'
                    error:
                        content: 'The content field is required.'
                ParentIdIsNotValidUUID:
                  value:
                    message: 'The parent id field must be a valid UUID.'
                    error:
                        parent_id: 'The parent id field must be a valid UUID.'
        '401':
          $ref: 'exceptions.yaml#/components/responses/userIsNotAuthorize'
        '404':
          description: Author or Event not exist
          content:
            application/json:
              schema:
                type: string
              examples:
                UserIsNotExist:
                  value: User is not found
                EventIsNotExist:
                  value: Event is not found
        '200':
          description: Successful created question
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
  /questions:
    get:
      tags:
        - Questions
      summary: Get all questions
      responses:
        '200':
          description: Successful displayed all questions
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        content:
                          type: string
                        event_id:
                          type: string
                          format: uuid
                        author_id:
                          type: string
                          format: uuid
                        parent_id:
                          type: string
                          format: uuid
                          nullable: true
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/questions?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/questions?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/questions?page=2
                  path:
                    type: string
                    example: http://localhost/api/questions
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

